### ISSUE TITLE
Support capture groups for replies

### ISSUE THREAD

**Issue by BooDoo** [BooDoo/CheapBotsTootSweet#3]
This could be cool, right? 

"If mention contains 1-6 characters of punctualphanumerics, separated from other text, return a variation on the 100 emoji containing that string":

```
{
	"[\s\b]([!-z]{1,6})[\s\b]": 
        "[word:#capture#]#svg_prefix##word##svg-suffix# {alt an emoji like \"100\" but it reads \"#word#\"} {hide}"
}
```

See `reply_for_account` in `backend/run_bots.js` - this might be more trouble than it's worth.

**Comment by BooDoo** [comment]
Some bare minimum prerequisites to considering implementation:  
  - Sanitize captured content to remove any CBTS meta tags [`{show}`, etc]
  - ANY reply using a capture group should be UNLISTED (at a minimum) and put behind a CW (boilerplate?) with media explicitly flagged as sensitive.
  - include [wordfilter](https://github.com/dariusk/wordfilter) with a very generous word set as a forced check
  - try to source cross-language equivalents to the wordfilter list

**Comment by serin-delaunay** [comment]
On twitter it would also be necessary to prevent use of hashtags and @-ing other accounts. Not sure how much Mastodon etiquette would differ on those issues, or if that limit should be imposed in CBTS or by the bot author in the reply regexes.

**Comment by BooDoo** [comment]
Totally agree that mentions should be off limits and enforced on the backend; should have mentioned that initially.

I believe Unlisted (or higher) privacy will take care of the hashtag spam concern, but would look further into that to make sure, if this feature is pursued.

**Comment by BooDoo** [comment]
Virtually no one has `does_replies` enabled; no way this is worth the effort.
